import Header from "@/layout/userpanel/Header";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "User App ",
  description: "Generated by News Company",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
      {/* <Footer/> */}
    </>
  );
}
