import Navbar from "@/layout/adminpanel/Navbar";
import Sidebar from "@/layout/adminpanel/Sidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
    title: "App (Admin)",
    description: "Generated by News Company",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className="flex h-screen bg-gray-100">

                {/* Sidebar */}
                <Sidebar />

                {/* Right Section */}
                <div className="flex flex-col flex-1 overflow-hidden">

                    {/* Navbar */}
                    <Navbar />

                    {/* Page Content */}
                    <main className="flex-1 overflow-y-auto p-6">
                        {children}
                    </main>

                </div>
            </div>
        </>
    );
}
